app1/urls.py
from django.urls import path
from app1.views import *
app_name='mavayya'

urlpatterns=[
    path('mawa/',mawa,name='mawa')
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
from app2.views import *
import app1
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('jaibalayya/',jaibalayya,name='jaibalayya'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def mawa(request):
    return render(request,'mawa.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def jaibalayya(request):
    return render(request,'jaibalayya.html')

templates/jaibalayya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>GENERIC AND SPECIFIC URL NAVIGATION IN JINJA TAGS</title>
</head>
<body>
    <center>
        <h1>THIS IS GENERIC URL NAVIGATION in jinja</h1>
        <h2><a href="{% url 'mavayya:mawa' %}">go to  jinja specific url navigation</a></h2>
    </center>
</body>
</html>

templates/mawa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>GENERIC AND SPECIFIC URL NAVIGATION IN JINJA TAGS</title>
</head>
<body>
    <center>
        <h1>this for specific url navigation in jinja</h1>
        <h2><a href="{% url 'jaibalayya' %}">go to jinja genric url navigation</a></h2>
    </center>
</body>
</html>